name: C/C++ CI

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache Protobuf
        id: cache-protobuf
        uses: actions/cache@v2.1.4
        with:
          path: /opt/protobuf
          key: ${{ runner.os }}-protobuf-compiled

      - name: Download and build Protobuf
        if: steps.cache-protobuf.outputs.cache-hit != 'true'
        working-directory: /opt/
        run: |
          git clone -b 3.11.x https://github.com/protocolbuffers/protobuf protobuf
          cd protobuf
          git submodule update --init --recursive
          ./autogen.sh
          ./configure
          make -j`nproc`
          make -j`nproc` check

      - name: Install Protobuf
        working-directory: /opt/protobuf
        run: |
          sudo make install
          sudo ldconfig

      - name: Install Ninja
        run: |
          sudo apt-get install ninja-build

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -GNinja
        
      - name: Build
        working-directory: build
        run: ninja
        
      - name: Test
        working-directory: build
        run: ctest -E ".*tcp.*"
