name: Build Conan packages

on: workflow_dispatch

jobs:
  build-package:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - {
              name: Windows MSVC Release,
              os: windows-2022,
              build_type: Release,
              cc: cl,
              cxx: cl,
              compiler_version: 17
            }
          - {
              name: Windows MSVC Debug,
              os: windows-2022,
              build_type: Debug,
              cc: cl,
              cxx: cl,
              compiler_version: 17
            }
          - {
              name: Ubuntu GCC Release,
              os: ubuntu-20.04,
              build_type: Release,
              cc: gcc-10,
              cxx: g++-10,
              compiler_version: 10
            }
          - {
              name: Ubuntu GCC Debug,
              os: ubuntu-20.04,
              build_type: Debug,
              cc: gcc-10,
              cxx: g++-10,
              compiler_version: 10
            }
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Install tools (Ubuntu)
        if: matrix.config.os == 'ubuntu-20.04'
        run: sudo apt-get install libgl-dev ninja-build

      - name: Install Conan
        run: |
          pip install conan
          conan config set general.revisions_enabled=1
          conan remote add davidbourgault https://artifactory.davidbourgault.ca/artifactory/api/conan/conan
          conan user -p ${{ secrets.CONAN_PASSWORD }} -r davidbourgault david

      - name: Create directories
        run: mkdir build

      - name: Install Third Parties (Ubuntu)
        if: matrix.config.os == 'ubuntu-20.04'
        working-directory: build
        run: conan install .. --update --build=missing -s compiler.version=${{ matrix.config.compiler_version}} -s compiler.libcxx=libstdc++11 -s build_type=${{ matrix.config.build_type }} -r davidbourgault

      - name: Install Third Parties (Windows)
        if: matrix.config.os == 'windows-2022'
        working-directory: build
        run: conan install .. --update --build=missing -s compiler="Visual Studio" -s compiler.version=${{ matrix.config.compiler_version}} -s build_type=${{ matrix.config.build_type }} -r davidbourgault

      - name: Upload
        run: conan upload '*' --remote davidbourgault --all --confirm
