name: C/C++ CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Protobuf
        working-directory: /opt/
        run: 'git clone -b 3.11.x https://github.com/protocolbuffers/protobuf protobuf'

      - name: Build Protobuf
        working-directory: /opt/protobuf
        run: 'autoconf && ./configure && make -j`nproc` && make -j`nproc` check'

      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: /opt/protobuf

      - name: Install Protobuf
        working-directory: /opt/protobuf
        run: 'make install'

      - name: Configure
        run: 'mkdir build && cd build && cmake .. -GNinja'
        
      - name: Build
        working-directory: build
        run: ninja
        
      - name: Test
        working-directory: build
        run: ninja test
