name: C/C++ CI

on: workflow_dispatch

jobs:
  build-qt:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - {
              name: Windows MSVC,
              os: windows-latest,
              build_type: Release,
              cc: cl,
              cxx: cl,
              generator: Visual Studio 16 2019
            }
          - {
              name: Ubuntu GCC,
              os: ubuntu-latest,
              build_type: Release,
              cc: gcc,
              cxx: g++,
              generator: Ninja
            }
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install tools (Ubuntu)
        if: matrix.config.os == 'ubuntu-latest'
        run: sudo apt-get install libgl-dev ninja-build

      - name: Install Conan
        run: |
          pip install conan
          conan remote add davidbourgault https://artifactory.davidbourgault.ca/artifactory/api/conan/conan
          conan user -p ${{ secrets.CONAN_PASSWORD }} -r davidbourgault david
          conan config set general.revisions_enabled=1

      - name: Create directories
        run: mkdir build

      - name: Install Third Parties (Ubuntu)
        if: matrix.config.os == 'ubuntu-latest'
        working-directory: build
        run: conan install .. -s compiler.libcxx=libstdc++11 -s build_type=${{ matrix.config.build_type }} -r davidbourgault --build=qt

      - name: Install Third Parties (Windows)
        if: matrix.config.os == 'windows-latest'
        working-directory: build
        run: conan install .. -s compiler="Visual Studio" -s compiler.version=16 -s build_type=${{ matrix.config.build_type }} -r davidbourgault --build=qt
      
      - name: Upload
        run: conan upload qt/* --remote davidbourgault --all --confirm